### ISSUE TITLE
browser side image resizing

### ISSUE THREAD

**Issue by 1stof8** [contao-components/dropzone#1]
Hi,
seit der v5.0.0 gibt es die Möglichkeit die Bilder vor dem Upload runter zu rechnen. Dies in Verbindung mit den Backendsettings für den Bildupload (Maximale Breite und Höhe) wäre ein sinnvolles Feature, da gerade für Endkunden der Upload vereinfacht würde. Meist haben sie Bilder mit zu hoher Auflösung.

PS: Greenhorn bzgl. github, Issues, … hoffe es ist dort an der richtigen Stelle.

**Comment by leofeyer** [comment]
Hatte ich schon getestet, aber die Qualität der im Browser verkleinerten Bilder ist deutlich schlechter als die der auf dem Server verkleinerten.

**Comment by 1stof8** [comment]
Danke für die Info. Aber vom Workflow wäre das echt hilfreich gewesen. Eine Checkbox, wenn man mit den Qualitätsverlusten leben kann, wäre ein Kompromiss. Dann schau ich doch mal, ob der upload mit ImageMagick eine bessere Alternative ist. Gehört aber hier nicht hin.
